---
- name: Install TPM apt packages
  apt:
    name:
      - tpm2-tools
    update_cache: true
- name: Undefine TPM2 memory space
  shell: tpm2_nvundefine 0x1500016
- name: Define TPM2 memory space
  shell: tpm2_nvdefine -s 128 0x1500016
- name: Generate root key
  shell: cat /dev/urandom | tr -dc ‘a-zA-Z0-9’ | head -c 128 > /root.key
- name: Save key to TPM2 memory space
  shell: tpm2_nvwrite -i /root.key 0x1500016
- name: Write key pull script
  shell: |
    cat << EOF > /usr/local/sbin/tpm2-getkey
    #!/bin/sh
    if [ -f ".tpm2-getkey.tmp" ]; then
    # tmp file exists, meaning we tried the TPM this boot, but it didn’t work for the drive and this must be the second
    # or later pass for the drive. Either the TPM is failed/missing, or has the wrong key stored in it.
    /lib/cryptsetup/askpass "Automatic disk unlock via TPM failed for \$CRYPTTAB_SOURCE (\$CRYPTTAB_NAME) Enter passphrase: "
    exit
    fi
    # No tmp, so it is the first time trying the script. Create a tmp file and try the TPM
    touch .tpm2-getkey.tmp
    
    tpm2_nvread 0x1500016
    EOF
- name: Set getkey permissions
  file:
    path: /usr/local/sbin/tpm2-getkey
    owner: root
    group: root
    mode: '750'
- name: Create initramfs hook
  shell: |
    cat << EOF > /etc/initramfs-tools/hooks/tpm2-decryptkey
    #!/bin/sh
    PREREQ=""
    prereqs()
    {
    echo ""
    }
    case \$1 in
    prereqs)
    prereqs
    exit 0
    ;;
    esac
    . /usr/share/initramfs-tools/hook-functions
    copy_exec `which tpm2_nvread`
    copy_exec /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0.0.0
    copy_exec /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0
    copy_exec /lib/cryptsetup/askpass
    exit 0
    EOF
- name: Set decryptkey permissions
  file:
    path: /etc/initramfs-tools/hooks/tpm2-decryptkey
    owner: root
    group: root
    mode: '755'
- name: Edit crypttab
  shell: cp /etc/crypttab /etc/crypttab.bak && sed -i 's%$%,keyscript=/usr/local/sbin/tpm2-getkey%' /etc/crypttab
- name: Backup the original initrd and create a new one
  shell: cp /boot/initrd.img-$(uname -r) /boot/initrd.img-$(uname -r).orig && mkinitramfs -o /boot/initrd.img-$(uname -r) $(uname -r)
- name: Tell user of next steps
  debug:
    msg: The TPM setup has been completed, but the key needs to be enrolled. Run "sudo cryptsetup luksAddKey /dev/nvme0n1p3 /root.key && sudo rm /root.key" and enter your encryption password when prompted.
- name: Tell user of next steps
  debug:
    msg: If there was already a key enrolled, delete the key from that slot by running "sudo cryptsetup luksKillSlot /dev/nvme0n1p3 [slot]."