- name: Download Zoom
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom.deb
    mode: '0755'
- name: Install Zoom
  shell: apt --fix-broken -y install /tmp/zoom.deb
- name: Remove the Zoom installer
  file:
    state: absent
    path: /tmp/zoom.deb
