---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=true
      changed_when: false
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Check that the conda exists
      stat:
        path: /opt/anaconda3/bin/conda
      register: conda_installed
    

  tasks:
    - include: tasks/zoom.yml
      when: "'zoom' not in ansible_facts.packages"
    - include: tasks/packages.yml
    - include: tasks/chrome.yml
      when: "'google-chrome-stable' not in ansible_facts.packages"
    - include: tasks/git-config.yml
    - include: tasks/nonessential.yml
    - include: tasks/conda.yml
      when: not conda_installed.stat.exists
