---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/zoom.yml
    - include: tasks/packages.yml
    - include: tasks/chrome.yml
    - include: tasks/git-config.yml
    - include: tasks/nonessential.yml
