- name: Install Conda
  block:
    - name: Download anaconda
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh
        dest: /tmp/install-anaconda.sh
        checksum: sha256:38ce717758b95b3bd0b1797cc6ccfb76f29a90c25bdfa50ee45f11e583edfdbf
        mode: 0550
    - name: Create conda folder
      become: True
      file:
        path: /opt/anaconda3
        state: directory
        owner: dsingh 
        mode: 755
        recurse: yes
    - name: Run the installer
      shell: /tmp/install-anaconda.sh -b -u -p /opt/anaconda3
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-anaconda.sh
    - name: Add anaconda bin to path
      shell: echo 'export PATH=/opt/anaconda3/bin:$PATH' >> /etc/profile
    - name: conda - read permission for all
      file:
        path: /opt/anaconda3
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      file:
        path: /opt/anaconda3/bin
        mode: +x
        recurse: yes
    - name: conda - install numpy pandas matplotlib scipy
      become: true
      become_user: dsingh
      shell: source activate base && conda install -y numpy pandas matplotlib scipy