- name: Install apt packages
  apt: 
    name: ['htop', 'nodejs', 'python3', 'powertop', 'nautilus-dropbox', 'git', 'docker.io', 'docker-compose']

- name: Install Discord and Microsoft To-Do
  snap:
    name: ['discord', 'ao']
    state: present
- name: Install VSCode Insider
  snap:
    name: code-insiders
    classic: yes
    state: present
- name: Install Authy
  snap:
    name: authy
    channel: latest/beta
    
- name: Set sudo alias for docker
  shell: 'alias docker="sudo /usr/bin/docker"' >> /home/dsingh/.bashrc
  become: true
  become_user: dsingh
    
