---
- name: Accept mscorefonts EULA
  shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  when: "'ttf-mscorefonts-installer' not in ansible_facts.packages"
- name: Add Nodejs Current PPA
  shell: curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
  when: "'nodejs' not in ansible_facts.packages"
- name: Add Yarn PPA 
  shell: curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  when: "'yarn' not in ansible_facts.packages"
- name: Add VSCode apt repository
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg && install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/ && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  when: "'code' not in ansible_facts.packages"
- name: Install heroku snap
  snap:
    name: heroku
    classic: yes
- name: Install Discord snap
  snap:
    name: discord
- name: Install Spotify snap
  snap:
    name: spotify
- name: Add dsingh to docker group
  shell: groupadd -f docker && usermod -aG docker dsingh && newgrp docker
- name: Download Discord Canary
  get_url:
    url: https://discord.com/api/download/canary?platform=linux&format=deb
    follow: yes
    dest: /home/dsingh/discord.deb
    mode: '0755'
  when: "'discord-canary' not in ansible_facts.packages"
- name: Install Discord
  shell: apt --fix-broken -y install /home/dsingh/discord.deb
  when: "'discord-canary' not in ansible_facts.packages"
- name: Remove the Discord installer
  file:
    state: absent
    path: /home/dsingh/discord.deb
- name: Install apt packages
  apt:
    name:
      - htop
      - python3
      - powertop
      - onedrive
      - docker.io
      - curl
      - docker-compose
      - geary
      - chrome-gnome-shell
      - fonts-crosextra-carlito
      - fonts-crosextra-caladea
      - ttf-mscorefonts-installer
      - apt-transport-https
      - nodejs
      - code
      - gcc
      - g++ 
      - make
      - yarn
      - build-essential
    update_cache: true

