- name: Accept mscorefonts EULA
  shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections

- name: Install apt packages
  apt: 
    name: ['htop', 'nodejs', 'python3', 'powertop', 'nautilus-dropbox', 'git', 'docker.io', 'docker-compose', 'geary', 'chrome-gnome-shell', 'fonts-crosextra-carlito', 'fonts-crosextra-caladea', 'ttf-mscorefonts-installer', 'freeipa-client', 'oddjob-mkhomedir']

- name: Install Discord, Microsoft To-Do, Postman
  snap:
    name: ['discord', 'ao', 'postman']
    state: present
- name: Install VSCode Insider
  snap:
    name: code-insiders
    classic: yes
    state: present
- name: Install Authy
  snap:
    name: authy
    channel: latest/beta

- name: read the passwd file
  shell: cat /home/dsingh/.bashrc
  register: bashrc
  
- name: Set sudo alias for docker
  shell: echo 'alias docker="sudo /usr/bin/docker"' >> /home/dsingh/.bashrc
  become: true
  become_user: dsingh
  when: bashrc.stdout.find('alias docker="sudo /usr/bin/docker"') == -1
