- name: Accept mscorefonts EULA
  shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
- name: Install apt packages
  apt: 
    name: ['htop', 'nodejs', 'python3', 'powertop', 'git', 'docker.io', 'curl', 'docker-compose', 'geary', 'chrome-gnome-shell', 'fonts-crosextra-carlito', 'fonts-crosextra-caladea', 'ttf-mscorefonts-installer']
- name: Add VSCode apt repository
  become: True
  become_user: root
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg && install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/ && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
- name: install heroku cli via snap
  become: true
  become_user: root
  command: snap install heroku --classic
- name: install discord via snap
  become: true
  become_user: root
  command: snap install discord
- name: Install VSCode
  apt:
    name: ['apt-transport-https', 'code']
    update_cache: yes
- name: read the bashrc file 
  shell: cat /home/dsingh/.bashrc
  register: bashrc
- name: Set sudo alias for docker
  become: true
  become_user: dsingh
  shell: echo 'alias docker="sudo /usr/bin/docker"' >> /home/dsingh/.bashrc
  when: bashrc.stdout.find('alias docker="sudo /usr/bin/docker"') == -1
- name: Download Discord Canary
  get_url:
    url: https://dl-canary.discordapp.net/apps/linux/0.0.114/discord-canary-0.0.114.deb
    dest: /home/dsingh/discord.deb
    mode: '0755'
- name: Install Discord
  become: true
  become_user: root
  shell: apt --fix-broken -y install /home/dsingh/discord.deb
