- name: Install apt packages
  apt: 
    name: ['htop', 'nodejs', 'python3', 'powertop', 'nautilus-dropbox']

- name: Install Discord
  snap:
    name: discord
    state: present
- name: Install VSCode Insider
  snap:
    name: code-insiders
    classic: yes
    state: present
- name: Install Authy
  snap:
    name: authy
    channel: latest/beta