- name: Accept mscorefonts EULA
  shell: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections

- name: Install apt packages
  apt: 
    name: ['htop', 'nodejs', 'python3', 'powertop', 'nautilus-dropbox', 'git', 'docker.io', 'docker-compose', 'geary', 'chrome-gnome-shell', 'fonts-crosextra-carlito', 'fonts-crosextra-caladea', 'ttf-mscorefonts-installer']
