- name: Download Zoom
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /home/dsingh/zoom.deb
    mode: '0755'
- name: Install Zoom
  become: true
  become_user: root
  shell: apt --fix-broken -y install /home/dsingh/zoom.deb
- name: Remove Zoom deb
  shell: rm /home/dsingh/zoom.deb
