---
- name: Install MacOS Packages
  hosts: localhost
  connection: local
  become: false
  vars:
    brew_cask_packages:
      - docker
      - firefox
      - google-chrome
      - google-drive
      - discord
      - spotify
      - visual-studio-code
      - betterdisplay
      - rectangle
      - mouse-fix
      - microsoft-office
      - cyberduck
      - postman
      - hpedrorodrigues/tools/dockutil
      - bitwarden
      - messenger
      - miniconda
    brew_packages:
      - tailscale
      - mas
      - nano
      - wget
      - gpg
      - gpg2
      - pinetry-mac
      - nvm
    # mas_packages: 
    #   - 497799835 # xcode
    mas_packages: []

    upgrade_homebrew_packages: true
  
    dockitems_remove:
      - Launchpad
      - TV
      - Podcasts
      - 'App Store'
      - Music

    dockitems_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app/"
        pos: 1
      - name: Messages
        path: "/Applications/Messages.app/"
        pos: 2
      - name: Spotify
        path: "/Applications/Spotify.app/"
        pos: 3
      - name: Mail
        path: "/System/Applications/Mail.app/"
        pos: 4
      - name: Discord
        path: "/Applications/Discord.app/"
        pos: 5
      - name: Messenger
        path: "/Applications/Messenger.app/"
        pos: 6
      - name: Visual Studio Code
        path: "/Applications/Visual Studio Code.app"
        pos: 7
      - name: Photos
        path: "/System/Applications/Photos.app/"
        pos: 8
      - name: Calendar
        path: "/System/Applications/Mail.app/"
        pos: 9
      - name: Notes
        path: "/System/Applications/Notes.app/"
        pos: 10
      - name: Terminal
        path: "/System/Applications/Utilities/Terminal.app/"
        pos: 11

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Workaround to have sudo rights until timestamp_timeout is raised
      command: "echo hi"
      become: yes

    - name: Installing Homebrew Cask Packages
      shell: /opt/homebrew/bin/brew install --cask {{item}}
      with_items: "{{ brew_cask_packages }}"

    - name: Workaround to have sudo rights until timestamp_timeout is raised
      command: "echo hi"
      become: yes

    - name: Installing Homebrew Packages
      shell: /opt/homebrew/bin/brew install {{item}}
      with_items: "{{ brew_packages }}"

    - name: Workaround to have sudo rights until timestamp_timeout is raised
      command: "echo hi"
      become: yes

    - name: Installing Mac App Store Packages
      shell: mas install {{item}}
      with_items: "{{ mas_packages }}"

    - name: Setup .zshrc
      ansible.builtin.template:
        src: files/.zshrc.j2
        dest: /Users/{{ ansible_user_id }}/.zshrc

    - name: Setup docker to use SSH context by default
      shell: docker context create lab --docker "host=ssh://dsingh@lab.ad.devksingh.com" && docker context use lab
      register: drc
      ignore_errors: true # if the context already exists then returns 1 but that's ok

    - name: Setup macOS defaults
      shell: |
        mkdir ~/.nvm
        defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true 
        defaults write com.apple.dock wvous-br-corner -int 0
        defaults write com.apple.dock wvous-br-modifier -int 0
        defaults write com.apple.dock wvous-tr-corner -int 0
        defaults write com.apple.dock wvous-tr-modifier -int 0
        defaults write com.apple.dock wvous-bl-corner -int 0
        defaults write com.apple.dock wvous-bl-modifier -int 0
        defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv"
        defaults write NSGlobalDomain "NSDocumentSaveNewDocumentsToCloud" -bool false
  
  roles:
    - geerlingguy.mac.dock