---
- name: Install MacOS Packages
  hosts: localhost
  connection: local
  become: false
  roles:
    - marcomc.macos_filevault2
  vars_prompt:
    - name: ansible_become_pass
      prompt: BECOME password
      private: true
  vars:
    filevault_showrecoverykey: yes
    filevault_user: "{{ ansible_user_id }}"
    filevault_user_password: "{{ ansible_become_pass }}"
    github_cloned_repos:
      - org: devksingh4
        repo: system-init
      - org: devksingh4
        repo: web
      - org: acm-uiuc
        repo: acm-uiuc.github.io
      - org: acm-uiuc
        repo: membership-api
      - org: acm-uiuc
        repo: resume-book
      - org: acm-uiuc
        repo: ticketing
    pip_packages:
      - numpy
      - matplotlib
      - pandas
      - scipy
      - scikit-learn
      - torch
      - torchvision
      - torchaudio
      - pytest
      - seaborn
    brew_cask_packages:
      - docker
      - firefox
      - google-chrome
      - google-drive
      - discord
      - spotify
      - visual-studio-code
      - betterdisplay
      - rectangle
      - mac-mouse-fix
      - cyberduck
      - postman
      - hpedrorodrigues/tools/dockutil
      - basictex 
      - zoom
      - raycast
      - messenger
      - slack
      - bitwarden
      - microsoft-office
    brew_packages:
      - gs
      - pdfgrep
      - tailscale
      - mas
      - nano
      - wget
      - gpg
      - gpg2
      - pinentry-mac
      - nvm
      - aws-sam-cli
      - node
      - python
      - cfn-lint
      - git
      - ffmpeg
      - zsh
    mas_packages: []
    upgrade_homebrew_packages: true

    dockitems_remove: []
    
    dockitems:
      - "/System/Library/CoreServices/Finder.app"
      - "/Applications/Google Chrome.app/"
      - "/Applications/Discord.app/"
      - "/Applications/Microsoft Outlook.app/"
      - "/Applications/Spotify.app/"
      - "/Applications/Messenger.app/"
      - "/Applications/Visual Studio Code.app"
      - "/Applications/Messages.app/"
      - "/System/Applications/Photos.app/"
      - "/Applications/Slack.app/"
      - "/System/Applications/Notes.app/"
      - "/System/Applications/Utilities/Terminal.app/"
      - "/Applications/Microsoft Remote Desktop.app/"
      - "/Applications/zoom.us.app/"

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

  tasks:
    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
        path: /opt/homebrew/bin
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present

    - name: Installing Mac App Store Packages
      shell: mas install {{item}}
      with_items: "{{ mas_packages }}"
      ignore_errors: yes

    - name: Create .ssh folder
      ansible.builtin.file:
        path: /Users/{{ ansible_user_id }}/.ssh
        state: directory

    - name: Setup .ssh/config
      ansible.builtin.template:
        src: files/ssh_config.j2
        dest: /Users/{{ ansible_user_id }}/.ssh/config

    - name: Remove all from Dock
      shell: dockutil --remove all --no-restart

    - name: Restart Dock
      shell: killall Dock
      become: yes

    - name: Add items to Dock
      shell: |
        dockutil --add '{{item}}' --no-restart
      with_items: "{{ dockitems }}"

    - name: Setup macOS defaults
      shell: |
        defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
        defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true 
        defaults write com.apple.dock wvous-br-corner -int 0
        defaults write com.apple.dock wvous-br-modifier -int 0
        defaults write com.apple.dock wvous-tr-corner -int 0
        defaults write com.apple.dock wvous-tr-modifier -int 0
        defaults write com.apple.dock wvous-bl-corner -int 0
        defaults write com.apple.dock wvous-bl-modifier -int 0
        defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv"
        defaults write NSGlobalDomain "NSDocumentSaveNewDocumentsToCloud" -bool false
        defaults write com.apple.dock autohide-time-modifier -float 0.3
        defaults write com.apple.dock "autohide" -bool true
        defaults write com.apple.dock "tilesize" -int "48"
        defaults write com.apple.TextEdit NSShowAppCentricOpenPanelInsteadOfUntitledFile -bool false

    - name: Restart Dock
      shell: killall Dock
      become: yes

    - name: Install Oh-my-ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      become: no
      when: lookup('env', 'ZSH') == ""

    - name: Setup .zshrc
      ansible.builtin.template:
        src: files/.zshrc
        dest: /Users/{{ ansible_user_id }}/.zshrc

    - name: Concatenate pip install list to string
      set_fact:
        pip_packages_str: "{{ pip_packages | join(' ') }}"

    - name: Install pip packages
      shell: |
        eval $(/opt/homebrew/bin/brew shellenv)
        pip3 install {{ pip_packages_str }}
      become: no

    - name: Setup source folder
      ansible.builtin.file:
        path: /Users/{{ ansible_user_id }}/source
        state: directory

    - name: Clone git repos
      shell: |
        if [ ! -d "/Users/{{ ansible_user_id }}/source/{{item.org}}/{{item.repo}}" ] ; then
          cd /Users/{{ ansible_user_id }}/source
          mkdir -p {{item.org}}
          cd {{item.org}}
          mkdir -p {{item.repo}}
          git clone https://github.com/{{item.org}}/{{item.repo}}
        fi
      loop: "{{ github_cloned_repos }} "
      ignore_errors: yes
