collections:
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: main
  - name: https://github.com/marcomc/ansible-role-macos-filevault2.git
    type: git
    version: master
